// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebScrapingData.Context;

namespace WebScrapingData.Migrations
{
    [DbContext(typeof(CustomerReviewContext))]
    partial class CustomerReviewContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("WebScrapingData.Model.Product", b =>
                {
                    b.Property<string>("IdProduct")
                        .HasColumnType("TEXT")
                        .HasColumnName("id_product");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT")
                        .HasColumnName("product_name");

                    b.HasKey("IdProduct");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("WebScrapingData.Model.Review", b =>
                {
                    b.Property<long>("IdReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_review");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT")
                        .HasColumnName("comment");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("review_date");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stars");

                    b.HasKey("IdReview");

                    b.ToTable("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
